package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.function.Supplier;

import org.littletonrobotics.junction.AutoLogOutput;

import com.ctre.phoenix6.Orchestra;
import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.configs.AudioConfigs;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.commands.PathfindingCommand;
import com.pathplanner.lib.config.ModuleConfig;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import com.pathplanner.lib.path.PathConstraints;
import com.pathplanner.lib.pathfinding.LocalADStar;
import com.pathplanner.lib.pathfinding.Pathfinding;

import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.kinematics.SwerveModuleState;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.math.system.plant.DCMotor;
import edu.wpi.first.units.measure.Angle;
import edu.wpi.first.units.measure.AngularVelocity;
import edu.wpi.first.units.measure.Distance;
import edu.wpi.first.units.measure.LinearVelocity;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.CommandScheduler;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.Constants;
import frc.robot.FieldLayout;
import frc.robot.Util.CustomSwerveRequests.FieldCentricCircularOrbit;
import frc.robot.Util.CustomSwerveRequests.FieldCentricGoToPoint;
import frc.robot.Util.CustomSwerveRequests.FieldCentricRestrictedRadius;
import frc.robot.generated.TunerConstants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    private Orchestra orchestra = new Orchestra();

    private Optional<SwerveRequest> currentRequest = Optional.empty();

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    // Swerve Requests to apply to Robot
    private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds();

    private final SwerveRequest.FieldCentric driveRequest = new SwerveRequest.FieldCentric()
            .withDeadband(Constants.linDeadband)
            .withRotationalDeadband(Constants.angDeadband)
            .withDriveRequestType(DriveRequestType.Velocity);

    private final SwerveRequest.FieldCentricFacingAngle gotoAngleRequest = new SwerveRequest.FieldCentricFacingAngle()
            .withRotationalDeadband(Constants.angDeadband)
            .withHeadingPID(10, 0, 0)
            .withDriveRequestType(DriveRequestType.Velocity);


    private final FieldCentricCircularOrbit orbitRequest = new FieldCentricCircularOrbit()
        .withRadiusCorrectionPID(3, 0, 0)
        .withHeadingPID(15, 0, 0)
        .withDriveRequestType(DriveRequestType.Velocity);

    private final FieldCentricGoToPoint goToRequest = new FieldCentricGoToPoint();
    

    private final FieldCentricRestrictedRadius orbitRestricteRadiusRequest = new FieldCentricRestrictedRadius()
        .withRadiusCorrectionPID(3, 0, 0)
        .withHeadingPID(15, 0, 0)
        .withDriveRequestType(DriveRequestType.Velocity);

    private final SwerveRequest.SwerveDriveBrake brakeRequest = new SwerveRequest.SwerveDriveBrake();
    private final SwerveRequest.Idle idleRequest = new SwerveRequest.Idle();

    // Pathplanner
    @SuppressWarnings("unused")
    private RobotConfig config = new RobotConfig(
            32,
            0.1,
            new ModuleConfig(
                    Inches.of(1.75).in(Meters),
                    TunerConstants.kSpeedAt12Volts.in(MetersPerSecond),
                    0.1,
                    DCMotor.getKrakenX60(1),
                    60,
                    1),
            Inches.of(25).in(Meters));

    /*
     * SysId routine for characterizing translation. This is used to find PID gains
     * for the drive motors.
     */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
            new SysIdRoutine.Config(
                    null, // Use default ramp rate (1 V/s)
                    Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    output -> setControl(m_translationCharacterization.withVolts(output)),
                    null,
                    this));

    /*
     * SysId routine for characterizing steer. This is used to find PID gains for
     * the steer motors.
     */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
            new SysIdRoutine.Config(
                    null, // Use default ramp rate (1 V/s)
                    Volts.of(7), // Use dynamic voltage of 7 V
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdSteer_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    volts -> setControl(m_steerCharacterization.withVolts(volts)),
                    null,
                    this));

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle
     * HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on
     * importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
            new SysIdRoutine.Config(
                    /* This is in radians per second², but SysId only supports "volts per second" */
                    Volts.of(Math.PI / 6).per(Second),
                    /* This is in radians per second, but SysId only supports "volts" */
                    Volts.of(Math.PI),
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdRotation_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    output -> {
                        /* output is actually radians per second, but SysId only supports "volts" */
                        setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                        /* also log the requested output for SysId */
                        SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
                    },
                    null,
                    this));

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
     * @param modules             Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }

        configurePathFinder();
        // Configure AutoBuilder last
        configureAutoBuilder();
        configureOrchestra();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }

        configurePathFinder();
        // Configure AutoBuilder last
        configureAutoBuilder();
        configureOrchestra();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve
     *                                  drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz
     *                                  on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry
     *                                  calculation
     *                                  in the form [x, y, theta]ᵀ, with units in
     *                                  meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision
     *                                  calculation
     *                                  in the form [x, y, theta]ᵀ, with units in
     *                                  meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            Matrix<N3, N1> odometryStandardDeviation,
            Matrix<N3, N1> visionStandardDeviation,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation,
                modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }

        configurePathFinder();
        // Configure AutoBuilder last
        configureAutoBuilder();
        configureOrchestra();
    }

    /**
     * Stores the current request before calling parent's copy of the method
     * 
     * @param request Swerve drive control request
     */
    @Override
    public void setControl(SwerveRequest request) {
        this.currentRequest = Optional.of(request);
        super.setControl(request);
    }

    /**
     * Returns a command that applies the specified control request to this swerve
     * drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test for Translation in the given direction 
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdTranslationQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineTranslation.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test for Translation in the given direction 
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdTranslationDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineTranslation.dynamic(direction);
    }

    /**
     * Runs the SysId Quasistatic test for steer in the given direction 
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdSteerQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineSteer.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test for steer in the given direction 
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdSteerDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineSteer.dynamic(direction);
    }
    
    /**
     * Runs the SysId Quasistatic test for rotation in the given direction 
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdRotationQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineRotation.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test for rotation in the given direction 
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdRotationDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineRotation.dynamic(direction);
    }

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply
         * it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts
         * mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is
         * disabled.
         * This ensures driving behavior doesn't ch\][ange until an explicit disable event
         * occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                        allianceColor == Alliance.Red
                                ? kRedAlliancePerspectiveRotation
                                : kBlueAlliancePerspectiveRotation);
                m_hasAppliedOperatorPerspective = true;
            });
        }

        SmartDashboard.putNumber("Operator Facing Mode", this.getOperatorForwardDirection().getDegrees());
        SmartDashboard.putNumber("Distance From Hub", FieldLayout.getHubDist(getPose2d().getTranslation()).in(Meters));
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the
     * odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision
     *                              camera.
     * @param timestampSeconds      The timestamp of the vision measurement in
     *                              seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the
     * odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters    The pose of the robot as measured by the
     *                                 vision camera.
     * @param timestampSeconds         The timestamp of the vision measurement in
     *                                 seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose
     *                                 measurement
     *                                 in the form [x, y, theta]ᵀ, with units in
     *                                 meters and radians.
     */
    @Override
    public void addVisionMeasurement(
            Pose2d visionRobotPoseMeters,
            double timestampSeconds,
            Matrix<N3, N1> visionMeasurementStdDevs) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds),
                visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is
     *         empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    private void configureAutoBuilder() {
        try {
            var config = RobotConfig.fromGUISettings();
            AutoBuilder.configure(
                    () -> getState().Pose, // Supplier of current robot pose
                    this::resetPose, // Consumer for seeding pose against auto
                    () -> getState().Speeds, // Supplier of current robot speeds
                    // Consumer of ChassisSpeeds and feedforwards to drive the robot
                    (speeds, feedforwards) -> setControl(
                            m_pathApplyRobotSpeeds.withSpeeds(ChassisSpeeds.discretize(speeds, 0.020))
                                    .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                                    .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())),
                    new PPHolonomicDriveController(
                            // PID constants for translation
                            new PIDConstants(13, 0, 0),
                            // PID constants for rotation
                            new PIDConstants(7, 0, 0)),
                    config,
                    // Assume the path needs to be flipped for Red vs Blue, this is normally the
                    // case
                    () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red,
                    this // Subsystem for requirements
            );
        } catch (Exception ex) {
            DriverStation.reportError("Failed to load PathPlanner config and configure AutoBuilder",
                    ex.getStackTrace());
        }
    }

    private void configurePathFinder(){
        Pathfinding.setPathfinder(new LocalADStar());
        CommandScheduler.getInstance().schedule(PathfindingCommand.warmupCommand());
    }

    private void configureOrchestra(){
        // for (int i = 0; i < 4; i ++){
        //     TalonFX targetMotor = this.getModule(i).getDriveMotor();
        //     orchestra.addInstrument(targetMotor);
        //     targetMotor.getConfigurator().apply(new AudioConfigs().withAllowMusicDurDisable(true));
        // }
        
        // orchestra.loadMusic("cry_for_me_ironmouse.chrp");
        // orchestra.play();
    }

    @AutoLogOutput
    public Pose2d getPose2d() {
        return this.getState().Pose;
    }

    @AutoLogOutput
    public SwerveModuleState[] getModuleStates() {
        return getState().ModuleStates;
    }

    @AutoLogOutput
    public ChassisSpeeds getChassisSpeeds() {
        return getState().Speeds;
    }

    /**
     * Checks if the robot orientation is within tolerance of a target angle
     *
     * @param tolerance check tolerance
     * @return True if the robot is controlling orientation and is within tolerance
     *         of the target. False otherwise.
     */
    public boolean atTargetAngle(Angle tolerance) {
        return currentRequest.isPresent() &&
                currentRequest.get() == gotoAngleRequest &&
                MathUtil.isNear(
                        gotoAngleRequest.TargetDirection.getDegrees(),
                        getPose2d().getRotation().getDegrees(),
                        tolerance.in(Degrees));
    }

    public Command getPathFindCmd(Pose2d targetPose, PathConstraints constraints){
        return AutoBuilder.pathfindToPoseFlipped(targetPose, constraints);
    }

    public Command getPathFindCmd(Pose2d targetPose, PathConstraints constraints, LinearVelocity endVelocity){
        return AutoBuilder.pathfindToPoseFlipped(targetPose, constraints, endVelocity);
    }

    /**
     * Creates a command to drive the drivetrain at field-centric linear and
     * angular velocities
     * 
     * @param xVel target x velocity
     * @param yVel target y velocity
     * @param rVel target angular velocity
     * @return command to run at the target velocities
     */
    public Command getDriveCmd(
            Supplier<LinearVelocity> xVel,
            Supplier<LinearVelocity> yVel,
            Supplier<AngularVelocity> rVel) {

        // Drivetrain will execute this command periodically
        return applyRequest(
                () -> driveRequest
                        .withVelocityX(xVel.get())
                        .withVelocityY(yVel.get())
                        .withRotationalRate(rVel.get()));

    }

    /**
     * Creates a command to drive the drivetrain at field-centric linear velocities
     * and maintain a target field-centric angle
     * 
     * @param xVel   target x velocity
     * @param yVel   target y velocity
     * @param target target angle
     * @return new gotoAngle Cmd
     */
    public Command gotoAngleCmd(
            Supplier<LinearVelocity> xVel,
            Supplier<LinearVelocity> yVel,
            Rotation2d target) {

        return applyRequest(
                () -> gotoAngleRequest
                        .withVelocityX(xVel.get())
                        .withVelocityY(yVel.get())
                        .withTargetDirection(target));
    }

    /**
     * Creates a command to drive the drivetrain at field-centric linear velocities
     * and orient the robot toward a point on the field
     * 
     * @param xVel   target x velocity
     * @param yVel   target y velocity
     * @param target target point to point towards
     * @param offset offset angle for the orientation
     * @return new lookAtPoint command
     */
    public Command lookAtPointCmd(
            Supplier<LinearVelocity> xVel,
            Supplier<LinearVelocity> yVel,
            Translation2d target,
            Rotation2d offset) {
        return applyRequest(
                () -> gotoAngleRequest
                        .withVelocityX(xVel.get())
                        .withVelocityY(yVel.get())
                        .withTargetDirection(
                                getPose2d().getTranslation().minus(target).getAngle().plus(offset)));
    }

    public Command travelSetSpeedCmd(Supplier<LinearVelocity> xVel, Supplier<LinearVelocity> yVel, Rotation2d targetAngle){
        return applyRequest(
            () -> gotoAngleRequest
                .withVelocityX(xVel.get())
                .withVelocityY(yVel.get())
                .withTargetDirection(targetAngle)
        );
    }

    /**
     * Creates a command to drive the drivetrain at field-centric linear velocities
     * and orient the robot toward the center of the current alliance hub
     * 
     * @param xVel   target x velocity
     * @param yVel   target y velocity
     * @param offset offset angle for the orientation
     * @return new lookAtHub command
     */
    public Command lookAtHubCmd(
            Supplier<LinearVelocity> xVel,
            Supplier<LinearVelocity> yVel,
            Rotation2d offset) {

        return lookAtPointCmd(xVel, yVel, FieldLayout.getHubCenter(), offset);
    }

    public Command hubOrbitCommand(Supplier<LinearVelocity> travelVel, Rotation2d offset, Distance radius){
        return applyRequest(() -> orbitRequest
            .withOrbitPoint(FieldLayout.getHubCenter())
            .withTravelVelocity(travelVel.get())
            .withRotationalOffset(offset)
            .withRadius(radius)
        )
        .finallyDo(() -> applyRequest(() -> idleRequest));
    }

    public Command towerAlignCommand(Supplier<LinearVelocity> travelVel, Rotation2d offset){
        return applyRequest(() -> goToRequest
            .withTargetPoint(FieldLayout.getTowerCenter())
            .withHeadingPID(15, 0, 0)
            .withTranslationPID(5, 0, 0)
            .withTravelVelocity(6)
            .withRotationalOffset(offset)
        )
        .finallyDo(() -> applyRequest(() -> idleRequest));
    }
    
    public Command hubOrbitRestrictedRadiusCommand(Supplier<LinearVelocity> travelVel, Supplier<LinearVelocity> radialVelocity, Rotation2d offset, Distance maxRadius, Distance minRadius){
        return applyRequest(() -> orbitRestricteRadiusRequest
            .withOrbitPoint(FieldLayout.getHubCenter())
            .withTravelVelocity(travelVel.get())
            .withRotationalOffset(offset)
            .withMaxRadius(maxRadius)
            .withMinRadius(minRadius)
            .withRadiusVelocity(radialVelocity.get())
        )
        .finallyDo(() -> applyRequest(() -> idleRequest));
    }

    /**
     * Crosses the swerve modules in an X pattern
     * 
     * @return new Brake Command
     */
    public Command brakeCmd() {
        return applyRequest(() -> brakeRequest);
    }

    /**
     * Gets a robot Idle Command
     * 
     * @return new idle command
     */
    public Command idleCmd() {
        return applyRequest(() -> idleRequest);
    }

    @AutoLogOutput
    public String getCommandString() {
        return this.getCurrentCommand() == null ? "null" : this.getCurrentCommand().getName();
    }
}
